version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - dotnet build WebAppForAPITest/SwapnapurtiWebsite.csproj
  post_build:
    commands:
      - dotnet publish -r linux-x64 WebAppForAPITest/SwapnapurtiWebsite.csproj
artifacts:  
  files:
    - WebAppForAPITest/bin/Debug/net8.0/publish/**/*
  discard-paths: yes
